## Settings.YAML file

# number of seeds
seeds: 10

# number of folds to split the data into - choose 1 for leave one out
folds: 10

# dataset: "Baseline" or "Follow-up"
dataset: "Baseline"

# tasks: ["PupilCalib", "CookieTheft", "Reading", "Memory"]
tasks: ["PupilCalib", "CookieTheft", "Reading", "Memory"]

# output type: "pixel" or "mm"
mode: "pixel"

# output_folder: specificy name as a string, will be added under ./results/LSTM/output_folder
# if nothing specified, automatically gets created with a name taking type of network, epochs, steps_per_epoch, version
output_folder: ""

# time length: the amount of seconds to choose data within - will start from the beginnning of PupilCalib
time: 40

# subsets: in a list: ["left", "right", "both_eyes", "avg", "all"]
subsets: ["left", "right", "both_eyes", "avg", "all"]

# classifiers: in a list: ["Dummy", "LinearReg", "NeuralNetwork", "Lasso", "Ridge"]
classifiers: ["Dummy", "LinearReg"]

# multiprocessing: to enable multiprocessing across seeds or not
multiprocessing: True

# multiprocessing number of cores
n_cores: {"nt": 6, "posix": -1}

# files for windows and ubuntu
paths:
  { "nt":
      { "input": "C:/Users/Anuj/Desktop/Canary/Baseline/OpenFace-eye-gaze",
        "output": "C:/Users/Anuj/Desktop/Canary/Baseline/eye_movement",
        "plog": "C:/Users/Anuj/Desktop/Canary/canary-nlp/datasets/csv_tables/participant_log.csv",
        "data": "C:/Users/Anuj/Desktop/Canary/Baseline/extracted_data/",
        "ttf": "C:/Users/Anuj/Desktop/Canary/Baseline/TasksTimestamps.csv",
        "pred_coords": "C:/Users/Anuj/Desktop/Canary/Baseline/predicted_coordinates/",
        "EMDAT_save_path": "C:/Users/Anuj/PycharmProjects/EMDAT-et-features-generation/src/data/TobiiV3/",
        "EMDAT_output_path": "C:/Users/Anuj/PycharmProjects/EMDAT-et-features-generation/src/outputfolder/",
        "ML_Framework_dataset": "C:/Users/Anuj/PycharmProjects/multimodal-ml-framework/datasets/",
        "et_processing_pipeline_raw_data_path": "C:/Users/"
      },
    "posix":
      { "input": "/home/anuj/OpenFace2/OpenFace/build/processed/Baseline/",
        "output": "/home/anuj/Documents/CANARY_Baseline/eye_movement/",
        "plog": "/home/anuj/multimodal-ml-framework/datasets/canary/participant_log.csv",
        "data": "/home/anuj/Documents/CANARY_Baseline/extracted_data/",
        "ttf": "/home/anuj/Documents/CANARY_Baseline/TasksTimestamps.csv",
        "pred_coords": "/home/anuj/Documents/CANARY_Baseline/predicted_coordinates/",
        "EMDAT_save_path": "/home/anuj/EMDAT-et-features-generation/src/data/TobiiV3/",
        "EMDAT_output_path": "/home/anuj/EMDAT-et-features-generation/src/outputfolder/",
        "ML_Framework_dataset": "/home/anuj/multimodal-ml-framework/datasets/",
        "et_processing_pipeline_raw_data_path": "/home/anuj/et-processing-pipeline/data/Preprocessing/Predicted_coords/"
      }
  }
