batch_size: null
bidirectional: false
data_dim_dict:
  all: 9
  average: 3
  both_eyes: 6
  left: 3
  right: 3
dropout: 0.05
epochs: 1000
final_length: 500
folds: 10
hidden_size: 256
input_size: 9
learning_rate: 0.001
max_seq_len: 100
network_type: GRU
num_layers: 2
outlier_threshold: 90
output_foldername: null
output_size: 2
pad_val: -1
pad_where: post
seeds: 1
strategy: all
subsets:
- left
- right
- both_eyes
- average
- all
tasks:
- CookieTheft
- Reading
truncate_where: post
val_set: true
verbose: true
